import React from 'react';

const IconFeather = () => (
// <!-- Generated by IcoMoon.io -->
<svg className="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16">
<title>quill</title>
<path d="M0 16c2-6 7.234-16 16-16-4.109 3.297-6 11-9 11s-3 0-3 0l-3 5h-1z"></path>
</svg>
)

export default IconFeather;